<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class LibrosSeeder extends Seeder
{
    public function run()
    {
        $db = \Config\Database::connect();

        $libros = [
            [
                'titulo'        => 'Matemática 1',
                'isbn'          => '9780306406001',
                'idtiporecurso' => 1,
                'idcategoria'   => 1,
                'descripcion'   => 'Libro de matemática para primer grado.',
                'anio'          => 2020,
                'numpaginas'    => 320,
                'portada'       => 'matematica_1.png',
                'autores'       => ['Juan Pérez'],
                'cantidad'      => 3,
            ],
            [
                'titulo'        => 'Física General',
                'isbn'          => '9780306406002',
                'idtiporecurso' => 1,
                'idcategoria'   => 2,
                'descripcion'   => 'Introducción a la física clásica y moderna.',
                'anio'          => 2019,
                'numpaginas'    => 450,
                'portada'       => 'fisica_general.jpg',
                'autores'       => ['Carlos Mendoza'],
                'cantidad'      => 2,
            ],
            [
                'titulo'        => 'Comunicación y Lenguaje',
                'isbn'          => '9780306406003',
                'idtiporecurso' => 1,
                'idcategoria'   => 3,
                'descripcion'   => 'Gramática y comprensión lectora.',
                'anio'          => 2021,
                'numpaginas'    => 280,
                'portada'       => 'comunicacion_y_lenguaje.png',
                'autores'       => ['María López'],
                'cantidad'      => 4,
            ],
            [
                'titulo'        => 'Historia del Perú',
                'isbn'          => '9780306406004',
                'idtiporecurso' => 1,
                'idcategoria'   => 1,
                'descripcion'   => 'Historia del Perú desde sus orígenes.',
                'anio'          => 2018,
                'numpaginas'    => 390,
                'portada'       => 'historia_del_peru.jpg',
                'autores'       => ['Luis Torres', 'Ana Ríos'],
                'cantidad'      => 2,
            ],
            [
                'titulo'        => 'Química Orgánica',
                'isbn'          => '9780306406005',
                'idtiporecurso' => 1,
                'idcategoria'   => 2,
                'descripcion'   => 'Fundamentos de química orgánica.',
                'anio'          => 2020,
                'numpaginas'    => 510,
                'portada'       => 'quimica_organica.jpg',
                'autores'       => ['Roberto Silva'],
                'cantidad'      => 3,
            ],
            [
                'titulo'        => 'Álgebra Lineal',
                'isbn'          => '9780306406006',
                'idtiporecurso' => 1,
                'idcategoria'   => 1,
                'descripcion'   => 'Vectores, matrices y transformaciones lineales.',
                'anio'          => 2022,
                'numpaginas'    => 360,
                'portada'       => 'algebra_lineal.webp',
                'autores'       => ['Patricia Vega'],
                'cantidad'      => 2,
            ],
            [
                'titulo'        => 'Biología Celular',
                'isbn'          => '9780306406007',
                'idtiporecurso' => 1,
                'idcategoria'   => 2,
                'descripcion'   => 'Estructura y función de la célula.',
                'anio'          => 2021,
                'numpaginas'    => 420,
                'portada'       => 'biologia_celular.jpg',
                'autores'       => ['Jorge Castro'],
                'cantidad'      => 3,
            ],
            [
                'titulo'        => 'Geografía del Perú',
                'isbn'          => '9780306406008',
                'idtiporecurso' => 1,
                'idcategoria'   => 3,
                'descripcion'   => 'Geografía física y humana del Perú.',
                'anio'          => 2019,
                'numpaginas'    => 300,
                'portada'       => 'geografia_del_peru.jpg',
                'autores'       => ['Carmen Flores'],
                'cantidad'      => 4,
            ],
            [
                'titulo'        => 'Introducción a la Programación',
                'isbn'          => '9780306406009',
                'idtiporecurso' => 1,
                'idcategoria'   => 1,
                'descripcion'   => 'Fundamentos de programación con Python.',
                'anio'          => 2023,
                'numpaginas'    => 340,
                'portada'       => 'introduccion_a_la_programacion.webp',
                'autores'       => ['Miguel Ángel Rojas'],
                'cantidad'      => 5,
            ],
            [
                'titulo'        => 'Cálculo Diferencial',
                'isbn'          => '9780306406010',
                'idtiporecurso' => 1,
                'idcategoria'   => 1,
                'descripcion'   => 'Fundamentos del cálculo diferencial e integral.',
                'anio'          => 2021,
                'numpaginas'    => 400,
                'portada'       => 'portada_null.png',
                'autores'       => ['Eduardo Ramírez'],
                'cantidad'      => 3,
            ],
            [
                'titulo'        => 'Estadística y Probabilidad',
                'isbn'          => '9780306406011',
                'idtiporecurso' => 1,
                'idcategoria'   => 1,
                'descripcion'   => 'Teoría y aplicaciones de la estadística.',
                'anio'          => 2020,
                'numpaginas'    => 380,
                'portada'       => 'portada_null.png',
                'autores'       => ['Sandra Huanca'],
                'cantidad'      => 2,
            ],
            [
                'titulo'        => 'Trigonometría',
                'isbn'          => '9780306406012',
                'idtiporecurso' => 1,
                'idcategoria'   => 1,
                'descripcion'   => 'Funciones trigonométricas y sus aplicaciones.',
                'anio'          => 2019,
                'numpaginas'    => 290,
                'portada'       => 'portada_null.png',
                'autores'       => ['Felipe Mendoza'],
                'cantidad'      => 4,
            ],
            [
                'titulo'        => 'Física Cuántica',
                'isbn'          => '9780306406013',
                'idtiporecurso' => 1,
                'idcategoria'   => 2,
                'descripcion'   => 'Introducción a la mecánica cuántica.',
                'anio'          => 2022,
                'numpaginas'    => 470,
                'portada'       => 'portada_null.png',
                'autores'       => ['Andrés Paredes'],
                'cantidad'      => 2,
            ],
            [
                'titulo'        => 'Termodinámica',
                'isbn'          => '9780306406014',
                'idtiporecurso' => 1,
                'idcategoria'   => 2,
                'descripcion'   => 'Leyes y principios de la termodinámica.',
                'anio'          => 2020,
                'numpaginas'    => 350,
                'portada'       => 'portada_null.png',
                'autores'       => ['Claudia Reyes'],
                'cantidad'      => 3,
            ],
            [
                'titulo'        => 'Electromagnetismo',
                'isbn'          => '9780306406015',
                'idtiporecurso' => 1,
                'idcategoria'   => 2,
                'descripcion'   => 'Campos eléctricos y magnéticos.',
                'anio'          => 2021,
                'numpaginas'    => 430,
                'portada'       => 'portada_null.png',
                'autores'       => ['Ricardo Soto'],
                'cantidad'      => 2,
            ],
            [
                'titulo'        => 'Química Inorgánica',
                'isbn'          => '9780306406016',
                'idtiporecurso' => 1,
                'idcategoria'   => 2,
                'descripcion'   => 'Estudio de compuestos inorgánicos.',
                'anio'          => 2019,
                'numpaginas'    => 370,
                'portada'       => 'portada_null.png',
                'autores'       => ['Verónica Lara'],
                'cantidad'      => 3,
            ],
            [
                'titulo'        => 'Bioquímica',
                'isbn'          => '9780306406017',
                'idtiporecurso' => 1,
                'idcategoria'   => 2,
                'descripcion'   => 'Procesos químicos en los seres vivos.',
                'anio'          => 2022,
                'numpaginas'    => 490,
                'portada'       => 'portada_null.png',
                'autores'       => ['Gabriela Mora'],
                'cantidad'      => 2,
            ],
            [
                'titulo'        => 'Genética y Evolución',
                'isbn'          => '9780306406018',
                'idtiporecurso' => 1,
                'idcategoria'   => 2,
                'descripcion'   => 'Herencia genética y teoría evolutiva.',
                'anio'          => 2021,
                'numpaginas'    => 410,
                'portada'       => 'portada_null.png',
                'autores'       => ['Pablo Gutiérrez'],
                'cantidad'      => 3,
            ],
            [
                'titulo'        => 'Ecología y Medio Ambiente',
                'isbn'          => '9780306406019',
                'idtiporecurso' => 1,
                'idcategoria'   => 2,
                'descripcion'   => 'Ecosistemas y conservación ambiental.',
                'anio'          => 2020,
                'numpaginas'    => 320,
                'portada'       => 'portada_null.png',
                'autores'       => ['Diana Castillo'],
                'cantidad'      => 4,
            ],
            [
                'titulo'        => 'Literatura Peruana',
                'isbn'          => '9780306406020',
                'idtiporecurso' => 1,
                'idcategoria'   => 3,
                'descripcion'   => 'Obras y autores de la literatura peruana.',
                'anio'          => 2018,
                'numpaginas'    => 350,
                'portada'       => 'portada_null.png',
                'autores'       => ['Rosa Villanueva'],
                'cantidad'      => 3,
            ],
            [
                'titulo'        => 'Filosofía y Ética',
                'isbn'          => '9780306406021',
                'idtiporecurso' => 1,
                'idcategoria'   => 3,
                'descripcion'   => 'Principales corrientes filosóficas y éticas.',
                'anio'          => 2019,
                'numpaginas'    => 300,
                'portada'       => 'portada_null.png',
                'autores'       => ['Héctor Quispe'],
                'cantidad'      => 2,
            ],
            [
                'titulo'        => 'Psicología General',
                'isbn'          => '9780306406022',
                'idtiporecurso' => 1,
                'idcategoria'   => 3,
                'descripcion'   => 'Fundamentos de la psicología humana.',
                'anio'          => 2021,
                'numpaginas'    => 360,
                'portada'       => 'portada_null.png',
                'autores'       => ['Lucía Benítez'],
                'cantidad'      => 3,
            ],
            [
                'titulo'        => 'Sociología',
                'isbn'          => '9780306406023',
                'idtiporecurso' => 1,
                'idcategoria'   => 3,
                'descripcion'   => 'Estudio de la sociedad y sus estructuras.',
                'anio'          => 2020,
                'numpaginas'    => 310,
                'portada'       => 'portada_null.png',
                'autores'       => ['Marco Delgado'],
                'cantidad'      => 2,
            ],
            [
                'titulo'        => 'Economía Básica',
                'isbn'          => '9780306406024',
                'idtiporecurso' => 1,
                'idcategoria'   => 3,
                'descripcion'   => 'Principios de microeconomía y macroeconomía.',
                'anio'          => 2022,
                'numpaginas'    => 340,
                'portada'       => 'portada_null.png',
                'autores'       => ['Silvia Coronado'],
                'cantidad'      => 3,
            ],
            [
                'titulo'        => 'Derecho Constitucional',
                'isbn'          => '9780306406025',
                'idtiporecurso' => 1,
                'idcategoria'   => 3,
                'descripcion'   => 'Constitución y derechos fundamentales del Perú.',
                'anio'          => 2019,
                'numpaginas'    => 280,
                'portada'       => 'portada_null.png',
                'autores'       => ['Ernesto Vargas'],
                'cantidad'      => 2,
            ],
            [
                'titulo'        => 'Inglés Básico',
                'isbn'          => '9780306406026',
                'idtiporecurso' => 1,
                'idcategoria'   => 3,
                'descripcion'   => 'Gramática y vocabulario básico del inglés.',
                'anio'          => 2021,
                'numpaginas'    => 260,
                'portada'       => 'portada_null.png',
                'autores'       => ['Natalia Cruz'],
                'cantidad'      => 5,
            ],
            [
                'titulo'        => 'Inglés Intermedio',
                'isbn'          => '9780306406027',
                'idtiporecurso' => 1,
                'idcategoria'   => 3,
                'descripcion'   => 'Habilidades comunicativas en inglés nivel B1.',
                'anio'          => 2022,
                'numpaginas'    => 290,
                'portada'       => 'portada_null.png',
                'autores'       => ['Natalia Cruz'],
                'cantidad'      => 4,
            ],
            [
                'titulo'        => 'Arte y Cultura',
                'isbn'          => '9780306406028',
                'idtiporecurso' => 1,
                'idcategoria'   => 3,
                'descripcion'   => 'Historia del arte y expresión cultural.',
                'anio'          => 2020,
                'numpaginas'    => 270,
                'portada'       => 'portada_null.png',
                'autores'       => ['Isabel Fuentes'],
                'cantidad'      => 3,
            ],
            [
                'titulo'        => 'Educación Física y Salud',
                'isbn'          => '9780306406029',
                'idtiporecurso' => 1,
                'idcategoria'   => 3,
                'descripcion'   => 'Actividad física y hábitos saludables.',
                'anio'          => 2021,
                'numpaginas'    => 220,
                'portada'       => 'portada_null.png',
                'autores'       => ['Omar Nieto'],
                'cantidad'      => 4,
            ],
            [
                'titulo'        => 'Matemática 2',
                'isbn'          => '9780306406030',
                'idtiporecurso' => 1,
                'idcategoria'   => 1,
                'descripcion'   => 'Continuación de matemática para segundo grado.',
                'anio'          => 2021,
                'numpaginas'    => 330,
                'portada'       => 'portada_null.png',
                'autores'       => ['Juan Pérez'],
                'cantidad'      => 3,
            ],
            [
                'titulo'        => 'Matemática 3',
                'isbn'          => '9780306406031',
                'idtiporecurso' => 1,
                'idcategoria'   => 1,
                'descripcion'   => 'Matemática avanzada para tercer grado.',
                'anio'          => 2022,
                'numpaginas'    => 350,
                'portada'       => 'portada_null.png',
                'autores'       => ['Juan Pérez'],
                'cantidad'      => 3,
            ],
            [
                'titulo'        => 'Física Aplicada',
                'isbn'          => '9780306406032',
                'idtiporecurso' => 1,
                'idcategoria'   => 2,
                'descripcion'   => 'Aplicaciones prácticas de la física.',
                'anio'          => 2020,
                'numpaginas'    => 400,
                'portada'       => 'portada_null.png',
                'autores'       => ['Carlos Mendoza'],
                'cantidad'      => 2,
            ],
            [
                'titulo'        => 'Química General',
                'isbn'          => '9780306406033',
                'idtiporecurso' => 1,
                'idcategoria'   => 2,
                'descripcion'   => 'Conceptos fundamentales de química.',
                'anio'          => 2019,
                'numpaginas'    => 380,
                'portada'       => 'portada_null.png',
                'autores'       => ['Roberto Silva'],
                'cantidad'      => 3,
            ],
            [
                'titulo'        => 'Anatomía Humana',
                'isbn'          => '9780306406034',
                'idtiporecurso' => 1,
                'idcategoria'   => 2,
                'descripcion'   => 'Estructura y sistemas del cuerpo humano.',
                'anio'          => 2021,
                'numpaginas'    => 460,
                'portada'       => 'portada_null.png',
                'autores'       => ['Jorge Castro'],
                'cantidad'      => 2,
            ],
            [
                'titulo'        => 'Historia Universal',
                'isbn'          => '9780306406035',
                'idtiporecurso' => 1,
                'idcategoria'   => 3,
                'descripcion'   => 'Grandes civilizaciones y eventos históricos.',
                'anio'          => 2018,
                'numpaginas'    => 420,
                'portada'       => 'portada_null.png',
                'autores'       => ['Luis Torres'],
                'cantidad'      => 3,
            ],
            [
                'titulo'        => 'Redacción y Ortografía',
                'isbn'          => '9780306406036',
                'idtiporecurso' => 1,
                'idcategoria'   => 3,
                'descripcion'   => 'Técnicas de escritura y reglas ortográficas.',
                'anio'          => 2020,
                'numpaginas'    => 240,
                'portada'       => 'portada_null.png',
                'autores'       => ['María López'],
                'cantidad'      => 4,
            ],
            [
                'titulo'        => 'Comprensión Lectora',
                'isbn'          => '9780306406037',
                'idtiporecurso' => 1,
                'idcategoria'   => 3,
                'descripcion'   => 'Estrategias para mejorar la comprensión de textos.',
                'anio'          => 2021,
                'numpaginas'    => 250,
                'portada'       => 'portada_null.png',
                'autores'       => ['María López'],
                'cantidad'      => 4,
            ],
            [
                'titulo'        => 'Lógica y Razonamiento',
                'isbn'          => '9780306406038',
                'idtiporecurso' => 1,
                'idcategoria'   => 1,
                'descripcion'   => 'Pensamiento lógico y razonamiento matemático.',
                'anio'          => 2022,
                'numpaginas'    => 300,
                'portada'       => 'portada_null.png',
                'autores'       => ['Eduardo Ramírez'],
                'cantidad'      => 3,
            ],
            [
                'titulo'        => 'Robótica y Automatización',
                'isbn'          => '9780306406039',
                'idtiporecurso' => 1,
                'idcategoria'   => 1,
                'descripcion'   => 'Fundamentos de robótica y sistemas automatizados.',
                'anio'          => 2023,
                'numpaginas'    => 360,
                'portada'       => 'portada_null.png',
                'autores'       => ['Miguel Ángel Rojas'],
                'cantidad'      => 2,
            ],
            [
                'titulo'        => 'Bases de Datos',
                'isbn'          => '9780306406040',
                'idtiporecurso' => 1,
                'idcategoria'   => 1,
                'descripcion'   => 'Diseño y gestión de bases de datos relacionales.',
                'anio'          => 2022,
                'numpaginas'    => 340,
                'portada'       => 'portada_null.png',
                'autores'       => ['Miguel Ángel Rojas'],
                'cantidad'      => 3,
            ],
            [
                'titulo'        => 'Redes y Comunicaciones',
                'isbn'          => '9780306406041',
                'idtiporecurso' => 1,
                'idcategoria'   => 1,
                'descripcion'   => 'Fundamentos de redes de computadoras.',
                'anio'          => 2021,
                'numpaginas'    => 320,
                'portada'       => 'portada_null.png',
                'autores'       => ['Patricia Vega'],
                'cantidad'      => 2,
            ],
            [
                'titulo'        => 'Seguridad Informática',
                'isbn'          => '9780306406042',
                'idtiporecurso' => 1,
                'idcategoria'   => 1,
                'descripcion'   => 'Principios de ciberseguridad y protección de datos.',
                'anio'          => 2023,
                'numpaginas'    => 310,
                'portada'       => 'portada_null.png',
                'autores'       => ['Miguel Ángel Rojas'],
                'cantidad'      => 3,
            ],
            [
                'titulo'        => 'Desarrollo Web',
                'isbn'          => '9780306406043',
                'idtiporecurso' => 1,
                'idcategoria'   => 1,
                'descripcion'   => 'HTML, CSS y JavaScript para desarrollo web.',
                'anio'          => 2023,
                'numpaginas'    => 380,
                'portada'       => 'portada_null.png',
                'autores'       => ['Miguel Ángel Rojas'],
                'cantidad'      => 4,
            ],
            [
                'titulo'        => 'Inteligencia Artificial',
                'isbn'          => '9780306406044',
                'idtiporecurso' => 1,
                'idcategoria'   => 1,
                'descripcion'   => 'Introducción a la IA y machine learning.',
                'anio'          => 2023,
                'numpaginas'    => 420,
                'portada'       => 'portada_null.png',
                'autores'       => ['Eduardo Ramírez'],
                'cantidad'      => 3,
            ],
            [
                'titulo'        => 'Gestión Empresarial',
                'isbn'          => '9780306406045',
                'idtiporecurso' => 1,
                'idcategoria'   => 3,
                'descripcion'   => 'Administración y gestión de empresas.',
                'anio'          => 2022,
                'numpaginas'    => 350,
                'portada'       => 'portada_null.png',
                'autores'       => ['Silvia Coronado'],
                'cantidad'      => 3,
            ],
        ];

        foreach ($libros as $libro) {
            $db->table('recursos')->insert([
                'titulo'        => $libro['titulo'],
                'isbn'          => $libro['isbn'],
                'idtiporecurso' => $libro['idtiporecurso'],
                'idcategoria'   => $libro['idcategoria'],
                'descripcion'   => $libro['descripcion'],
                'anio'          => $libro['anio'],
                'numpaginas'    => $libro['numpaginas'],
                'portada'       => $libro['portada'],
            ]);
            $idRecurso = $db->insertID();

            $db->table('activos')->insert([
                'titulo'              => $libro['titulo'],
                'idcategoria'         => $libro['idcategoria'],
                'idtiporecurso'       => $libro['idtiporecurso'],
                'cantidad_total'      => $libro['cantidad'],
                'cantidad_disponible' => $libro['cantidad'],
                'estado'              => 'disponible',
                'autor'               => implode(', ', $libro['autores']),
                'foto'                => $libro['portada'],
            ]);

            foreach ($libro['autores'] as $nombreAutor) {
                $autor = $db->table('autores')
                    ->where('nombre', $nombreAutor)
                    ->get()
                    ->getRowArray();

                if (!$autor) {
                    $db->table('autores')->insert(['nombre' => $nombreAutor]);
                    $idAutor = $db->insertID();
                } else {
                    $idAutor = $autor['idautor'];
                }

                $db->table('recurso_autor')->insert([
                    'idrecurso' => $idRecurso,
                    'idautor'   => $idAutor,
                ]);
            }
        }

        echo "9 libros insertados correctamente.\n";
    }
}
